### PR TITLE
Add code splitting

### PR DESCRIPTION
**Pull request by PPrakapavicius**

### CODE REVIEW

**Review by domzic — APPROVED** [review]

**Review by benNek — APPROVED** [review]

**Review by rikius — APPROVED** [review]

**Comment by rikius** [comment]
I guess 404 pages are broken: https://app.petbook.lt/dont-exists. 

Notice there is no content and error loading content is missing.

**Comment by PPrakapavicius** [comment]
I believe url for 404 is https://app.petbook.lt/not-found

**Comment by rikius** [comment]
yes, but when trying to load the page that it should show https://app.petbook.lt/not-found - instead of showing empty content: https://app.petbook.lt/aaa

**Comment by domzic** [comment]
@rikius  We don't have such route setup yet. We just showing it on particular `/not-found` page:
`                            <Route
                                exact
                                path="/not-found"
                                component={React.lazy(() => import('./pages/PageNotFound'))}
                            />`

**Comment by domzic** [comment]
If we would want to show PageNotFound for all not existing URL's, we should add 
`<Route component={React.lazy(() => import('./pages/PageNotFound'))} />` at the end of all routes

**Pull request merged**
